'\" t
.\"     Title: sourcehawk
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-11-02
.\"    Manual: Sourcehawk Manual
.\"    Source: Sourcehawk v0.1.4
.\"  Language: English
.\"
.TH "SOURCEHAWK" "1" "2020-11-02" "Sourcehawk v0.1.4" "Sourcehawk Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
sourcehawk \- Watch over your source like a hawk...
.SH "SYNOPSIS"
.sp
\fBsourcehawk\fP [\fB\-hV\fP] [COMMAND]
.SH "DESCRIPTION"
.sp
Watch over your source like a hawk...
.SH "OPTIONS"
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Show this help message and exit.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print version information and exit.
.RE
.SH "COMMANDS"
.sp
\fBhelp\fP
.RS 4
Displays help information about the specified command
.RE
.sp
\fBscan\fP, \fBflyover\fP, \fBsurvey\fP
.RS 4
Runs a scan on the source code
.RE
.sp
\fBvalidate\-config\fP, \fBvc\fP
.RS 4
Validate configuration
.RE
.sp
\fBfix\fP, \fBcorrect\fP, \fBresolve\fP
.RS 4
Fix source based on configuration
.RE